#### 1. 异常

##### 1.1. Exception和Error的区别

​    在Java中，`java.lang`包下的`Throwable`类是所有异常的祖先，`Throwable`类两个重要的子类：

* `Exception`：程序本身可以处理的异常，通过`try-catch`进行捕获。`Exception`又可分为`Checked Exception`(受检异常，必须处理)和`Unchecked Exception`(不受检异常，可以不处理)；

* `Error`：属于程序无法处理的错误，不建议通过`try-catch`进行捕获。例如Java虚拟机允许错误`Vitual MachineError`，虚拟机内存不够错误`OutOfMemoryError`，类定义错误`NoClassDefFoundError`等。这些异常发生时，`Java`虚拟机(`JVM`)一般会选择线程终止。

##### 1.2. CheckedException和UncheckedException的区别

* `Checked Exception`即受检异常，Java代码在编译过程中，如果受检异常没有被`catch`或者`throws`关键字处理的话，就没有办法通过编译。除了`RuntimeException`及其子类以外，其他的Exception类及其子类都属于受检异常。常见的受检异常有IO相关的异常，`ClassNotFoundException`，`SqlException`......。

* `Unchecked Exception`即不受检查异常，在Java代码编译过程中，我们即使不处理不受检查异常，也可以正常通过编译。RuntimeException及其子类统称为非受检异常，常见的有:`NullPointerException`(空指针异常)、`IllegalArgumentException`(参数错误比如方法入参类型错误)、`NumberFormatException`(字符串转为数字格式错误，IllegalArgumentException的子类)、`ArrayIndexOutOfBoundsException`(数组越界错误)、`ArithmeticException`(算术错误)、`SecurityException`(安全错误比如权限不够)、`UnsupportedOperationException`(不支持的操作错误比如重复创建同一用户)、`......`

##### 1.3. Throwable类常用方法

- `String getMessage()`：返回异常发生时的简要描述
- `String toString()`：返回异常发生时的详细信息
- `String getLocalizedMessage()`: 返回异常对象的本地化信息。使用Throwable的子类覆盖这个方法，可以生成本地化信息。如果子类没有覆盖该方法，则该方法返回的信息与`getMessage()`返回的结果相同。
- `void prinStackTrace()`：在控制台打印`Throwable`对象封装的异常信息。

##### 1.4. 异常使用注意点

- 勿把异常定义为静态变量，每次手动抛出异常，都需要手动new一个异常对象抛出。

- 抛出的异常要有意义。

- 建议抛出更加具体的异常如字符串转换为数字格式错误时应抛出NumberFormatException而不是其父类IllegalArgumentException。

- 使用日志打印之后最好不要再抛出异常。

#### 2. 异常处理

##### 2.1. try-catch-finally用法

- `try`块：用于捕获异常，其后可接0个或多个catch块，如果没有catch块，则必须跟一个finally块。

- `catch`块：用于处理try捕获到的异常

- `finally`块：无论是否捕获或处理异常，finally块里的语句都会被执行，当在try块或者catch块中遇到return语句时，finally语句块将在方法返回之前被执行。

  ```java
    try{
        System.out.println("try to test 'try-catch-finally'");
        throw new RuntimeException("RuntimeException");
    }catch(Exception e){
        System.out.println("Catch Exception -> " + e.getMessage());
    }finally{
        System.out.println("Finally");
    }
  
  /**
    Result：
  
    try to test 'try-catch-finally'
    Catch Exception -> RuntimeException
    Finally
  **/
  ```

  

  当try语句和finally语句中都有return语句时，try语句块中的return语句就会被忽略。原因：try语句中的return返回值会被暂存在一个本地变量中，当执行到finally语句中的return之后，这个本地变量的值就变成了finally语句中的return返回值。

  

  ```java
    public  void testFinally() {
        System.out.println(f(2));
    }
  
    public int f(int value) {
        try {
            return value * value;
        } finally {
            if (value == 2) {
                return 0;
            }
        }
    }
  /**
    Result：
  
    0
  **/
  ```

  

  finally中的代码一定会执行么？不一定！在某些情况下，finally中的代码不会被执行！如：finally之前虚拟机被终止执行，程序所在的线程死亡；关闭CPU。

  

  ```java
   try{
        System.out.println("try to test 'try-catch-finally'");
        throw new RuntimeException("RuntimeException");
    }catch(Exception e){
        System.out.println("Catch Exception -> " + e.getMessage());
    }finally{
        System.out.println("Finally");
    }
  
  /**
    result：
    
    Try to do something
    Catch Exception -> RuntimeException
  **/
  ```

##### 2.2.try-with-resource用法

- 适用范围：任何实现`java.lang.AutoCloseable`或者`java.io.Closeable`的对象。

- 关闭资源和finally块的执行顺序：在try-with-resources语句中，任何catch和finally块在声明的资源关闭后运行。

- 《Effective Java》中对于必须要关闭的资源，推荐使用try-with-resources语句。

- 代码演变：

  ```java
    //读取文本文件的内容(try-catch-finally)
    Scanner scanner = null;
    try {
        scanner = new Scanner(new File("D://read.txt"));
        while (scanner.hasNext()) {
            System.out.println(scanner.nextLine());
        }
    } catch (FileNotFoundException e) {
        e.printStackTrace();
    } finally {
        if (scanner != null) {
            scanner.close();
        }
    }
  ```

  

  ```java
  	 //After Java 7 : try-with-resources  
  	 try (Scanner scanner = new Scanner(new File("test.txt"))) {
          while (scanner.hasNext()) {
              System.out.println(scanner.nextLine());
          }
      } catch (FileNotFoundException fnfe) {
          fnfe.printStackTrace();
      }
  ```

  通过使用分号分隔，可以在`try-with-resources`块中声明多个资源。